language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-3.3.1
    - android-27
    - extra-android-m2repository


before_install:
    - chmod +X gradlew
    
script:
    - ls
    - ./gradlew assembleDebug
    #- ./gradlew connectedAndroidTest coveralls
