language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-3.3.1

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    
    # Emulator Management: Create, Start and Wait
before_install:
    - chmod +X gradlew
  
script:
  #- ./gradlew build
  - ls
  - ./gradlew assembleDebug
  - ./gradlew connectedAndroidTest coveralls
