CREATE TABLE USER_INFORMATION(
NAME VARCHAR(50),
STUDENT_NUMBER INT(10) NOT NULL UNIQUE,
EMAIL_ADDRESS VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
COURSE_1 VARCHAR(20),
COURSE_2 VARCHAR(20),
COURSE_3 VARCHAR(20),
COURSE_4 VARCHAR(20),
COURSE_5 VARCHAR(20),
TRANSCRIPT VARCHAR(100));

CREATE TABLE BOOKINGS(
COURSE VARCHAR(10),
VENUE VARCHAR(50),
TIME_TUTORED TIME,
TUTOR_1 VARCHAR(50),
TUTOR_2 VARCHAR(50),
TUTOR_3 VARCHAR(50),
TUTOR_4 VARCHAR(50),
TUTOR_5 VARCHAR(50),
TUTOR_6 VARCHAR(50),
TUTOR_7 VARCHAR(50));
