CREATE TABLE BOOKINGS(
NAME VARCHAR(20) NOT NULL,
STUDENT_NUMBER VARCHAR(10) NOT NULL UNIQUE,
COURSE VARCHAR(10) DEFAULT NULL,
DATE_TUTORED DATE NOT NULL,
VENUE VARCHAR(50) DEFAULT NULL,
START_TIME TIME DEFAULT NULL,
END_TIME TIME NOT NULL,
VALID TINYINT(1) NOT NULL);



CREATE TABLE USER_INFORMATION(
NAME VARCHAR(50) DEFAULT NULL,
STUDENT_NUMBER INT(10) NOT NULL UNIQUE,
EMAIL_ADDRESS VARCHAR(50) NOT NULL,
USER_PASSWORD VARCHAR(50) NOT NULL,
ADMIN TINYINT(1) DEFAULT NULL,
COURSE_1 VARCHAR(20) DEFAULT NULL,
COURSE_2 VARCHAR(20) DEFAULT NULL,
COURSE_3 VARCHAR(20) DEFAULT NULL,
COURSE_4 VARCHAR(20) DEFAULT NULL,
COURSE_5 VARCHAR(20) DEFAULT NULL,
TRANSCRIPT VARCHAR(100) DEFAULT NULL);